### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by KC135Q** [KC135Q/keysnstuff#6]

**Comment by KC135Q** [comment]
- [ ] “In writing”: Can be word, pdf, notes, vs markdown, post, snippet, whatever... should have a team message thread or channel (recommended) in Slack. Invite your assigned TA and your instructor to that communication method.
- [ ] Team Name (optional)
- [x] Title
- [ ] Description
- [ ] User Stories (at least one)
- [ ] Roles, Wireframe
- [ ] API List with functional GET (cUrl, Postman or Insomnia)
- [ ] Timeline (So important!)
- [ ] Deploy the skeleton (GitHub guru should deploy regularly)*
- [ ] Individual Roles (some may have more than one)
- [ ] Project Manager
- [ ] GitHub Guru
- [ ] Data Flow Doctor (Optional)
- [ ] API Researcher (Can be combined with Data Flow)
- [ ] Presentation Proctor
- [ ] HTML Expert
- [ ] CSS
- [ ] JavaScript (Primary… everyone should have some part of the JS)

**Comment by KC135Q** [comment]
- [x] Title: 
- [x] Description:
